[project]
name = "temporal-throttling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=6.0.0",
    "redis>=6.1.0",
    "temporalio>=1.11.1",
]
